### ISSUE TITLE
Accuracy very low

### ISSUE THREAD

**Issue by thehitechpanky** [anubhavshrimal/FaceRecognition#3]
Hey your code is superb and it does the job, but it's accuracy is very low...

**Comment by thehitechpanky** [comment]
Perhaps using https://github.com/ageitgey/face_recognition instead of face_recognition_api.py might help

**Comment by anubhavshrimal** [comment]
Hi, I have updated the code, now it uses K-Nearest Neighbors approach which increases the accuracy.
Though in this approach it will not show the confidence percentage.
