### ISSUE TITLE
Images not being encoded

### ISSUE THREAD

**Issue by ankithmullangi** [anubhavshrimal/FaceRecognition#6]
Hello Anubhav,

Greatly appreciate the work done!
I'm currently facing problems in importing the images and training the algorithm
As per the tutorial after the encoding of the images, the classes needs to be created but i'm getting 0 classes created after running the Encoding code.
Please find the attached image.
This project is really important part of my bachelors project.

Please do the needful,
![untitled](https://user-images.githubusercontent.com/40245465/41368736-14966558-6f43-11e8-95ce-fe641b2f993d.png)
Thanks and Regards,
Ankith

**Comment by anubhavshrimal** [comment]
use python 3, not 2.7

**Comment by ankithmullangi** [comment]
Hello Anubhav,

Thanks for the reply
As you suggested me to install 3 instead of 2.7.
I have tried doing the same.
But the error still persists
Could you please debug this problem.

Thanks and Regards,
Ankith



*---Thanks and Regards,Ankith Rajashekar Mullangi,*
